# Generated by Django 6.0.2 on 2026-03-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
