# Generated by Django 6.0.2 on 2026-03-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
